### ISSUE TITLE
monad-logger should reexport `fromLogStr`

### ISSUE THREAD

**Issue by merijn** [snoyberg/monad-logger#13]
I'm writing my own MonadLogger implementation which means that I have to output the `LogStr` produced by `defaultLogStr`, however monad-logger doesn't currently re-export `fromLogStr` from fast-logger, which means adding an extra explicit dependency on fast-logger and an extra import, which isn't a big deal, but there doesn't seem to be any compelling reason why monad-logger couldn't/shouldn't reexport `fromLogStr` considering it already reexports a bunch of other stuff...

**Comment by snoyberg** [comment]
No objection, PR welcome.
