### ISSUE TITLE
Export `LogLine`?

### ISSUE THREAD

**Issue by johannesgerer** [snoyberg/monad-logger#15]
[`LogLine`](https://github.com/snoyberg/monad-logger/blob/8732ceae23142e60f93540d729e2fd0f7a8d0e1e/Control/Monad/Logger.hs#L412) is not exported. Is this intentional?

**Comment by snoyberg** [comment]
No, PR welcome to export it. The `@since` comment should be updated to reflect the new minor version.

**Comment by sestrella** [comment]
@snoyberg I think this one was already solved by https://github.com/snoyberg/monad-logger/pull/19

**Comment by snoyberg** [comment]
Good catch thanks!
