### ISSUE TITLE
msg type for non-TH logging specialised to Text

### ISSUE THREAD

**Issue by mpilgrem** [snoyberg/monad-logger#24]
The non-TH logging functions were introduced in `monad-logger-0.3.2.0`. They are built on `logWithoutLoc`, which has been exported since `0.3.23`, or `logCS`. The type of `logWithoutLoc` is:

```haskell
logWithoutLoc :: (MonadLogger m, ToLogStr msg) => LogSource -> LogLevel -> msg -> m ()
```
but the logging functions are more specialised in the message type (`Text`), for example:

```haskell
logDebugNS :: MonadLogger m => LogSource -> Text -> m ()
logDebugNS src = logWithoutLoc src LevelDebug
```

`logCS` also has a generalised `msg`.

Is there anything preventing these functions from having the more general type (given that a `Text` instance for `toLogStr msg` is exported)? For example:

```haskell
logDebugNS :: (MonadLogger m, ToLogStr msg) => LogSource -> msg -> m ()
```

If there is not a barrier, I will propose a pull request.

**Comment by snoyberg** [comment]
Making such a change is a breaking change, since it breaks type inference. That's generally why Text can be preferable

**Comment by mpilgrem** [comment]
Thank you. I'll close the issue then.
