### ISSUE TITLE
Couldn't match LoggingT with NoLoggingT

### ISSUE THREAD

**Issue by KristianBalaj** [snoyberg/monad-logger#30]
I have a problem with composing functions with `LoggingT` and `NoLoggingT`.

I want to be able to turn off logging and I've seen the `LoggingT` and `NoLoggingT` types. So I'm trying to use the `runFileLoggingT` and `runNoLoggingT` functions to run my monad transformer but probably there seems to be a problem with `LoggingT` type in the monad stack. 

The following code snippet:

<details>
<summary>Code example that is failing to typecheck</summary>

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

module App (MyApp (), runMyApp) where

import CmdLine (Params (..))
import Control.Monad.Logger (LoggingT, MonadLogger)
import Control.Monad.Logger.CallStack (runFileLoggingT)
import Control.Monad.State (MonadIO, MonadState, StateT (..))
import Types (Direction)

newtype MyApp a = MyApp
  { runApp :: StateT Direction (LoggingT IO) a
  }
  deriving (Functor, Applicative, Monad, MonadIO, MonadState Direction, MonadLogger)

runMyApp :: Params -> MyApp a -> Direction -> IO (a, Direction)
runMyApp (Params _ True) app st = runFileLoggingT "log.log" (runStateT (runApp app) st)
runMyApp (Params _ False) app st = runNoLoggingT (runStateT (runApp app) st)
```
</details>

**How should I compose this to achieve what I'm expecting? If this is not possible, what is the purpose of the `NoLoggingT` transformer?**

**Comment by snoyberg** [comment]
In a case like this, you would want `MyApp` to be generic over the underlying monad, something like:

```haskell
newtype MyApp m a = MyApp
  { runApp :: StateT Direction m a
  }
```

**Comment by emlautarom1** [comment]
Would it be possible to do something like this:


```haskell
runMyApp (Params _ enableLogging) app st = (if enableLogging then runFileLoggingT "log.log" else runNoLoggingT) (runStateT (runApp app) st)
```

I'm using conduit and I have a long pipeline so I would like to avoid duplicating it in both branches. Here we are duplicating `runStateT (runApp app) st)` but for me it's very inconvenient to do something similar.

At the end of the day what I want is to have something like:

```haskell
let runLogger =
        if debugMode
          then runStdoutLoggingT
          else runNoLoggingT

runLogger . runResourceT . runConduit $ ...
```

**Comment by snoyberg** [comment]
No, that's not going to typecheck. You'd need to either have a shared type that can represent both the logging and not-logging case, or extract the common code to another function with a typeclass-generic implementation. Both approaches would work. The code I showed above with a generic `m` is in the right direction for this.
